### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by jaylac2000** [arclegrandroi/rtp-pmmp#1]
make it so if you run /rtp it randomly teleports you in 1 of the worlds in the config , i was planning on forcing players out of my factions spawn into another world using /rtp but it doesnt work like that

**Comment by Arcoz0308** [comment]
That the player are teleport to one random world?

**Comment by jaylac2000** [comment]
So when they do /rtp it should teleport them to a random world?

**Comment by jaylac2000** [comment]
In my spawn world you cannot run /rtp even though i have 2 other worlds for game play in the config, but it doesnt teleport them there

**Comment by Arcoz0308** [comment]
in order for random teleportation to work in another world the player must be in another world
